[[constraint]]
  name = "cloud.google.com/go"
  revision = "81b7822b1e798e8f17bf64b59512a5be4097e966"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v10.3.0-beta"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "v8.3.1"

[[constraint]]
  name = "github.com/Azure/go-ntlmssp"
  revision = "c92175d540060095c69ced311f76aea56c83ecdb"

[[constraint]]
  name = "github.com/ChrisTrenkamp/goxpath"
  revision = "4fe03583929022c9c96829401ffabc755e69782e"

[[constraint]]
  name = "github.com/Unknwon/com"
  version = "v1"

[[constraint]]
  name = "github.com/agext/levenshtein"
  version = "v1.2.1"

[[constraint]]
  name = "github.com/agl/ed25519"
  revision = "278e1ec8e8a6e017cd07577924d6766039146ced"

[[constraint]]
  name = "github.com/antchfx/xpath"
  revision = "b5c552e1acbdd77b5e369eab0efd1e0f9d7090e4"

[[constraint]]
  name = "github.com/antchfx/xquery"
  revision = "eb8c3c17260731e52f9420af1508a47bfaf217a8"

[[constraint]]
  name = "github.com/apparentlymart/go-cidr"
  revision = "2bd8b58cf4275aeb086ade613de226773e29e853"

[[constraint]]
  name = "github.com/apparentlymart/go-textseg"
  revision = "b836f5c4d331d1945a2fead7188db25432d73b69"

[[constraint]]
  name = "github.com/armon/circbuf"
  revision = "bbbad097214e2918d8543d5201d12bfd7bca254d"

[[constraint]]
  name = "github.com/armon/go-radix"
  revision = "4239b77079c7b5d1243b7b4736304ce8ddb6f0f2"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "v1.10.36"

[[constraint]]
  name = "github.com/bgentry/go-netrc"
  revision = "9fd32a8b3d3d3f9d43c341bfe098430e07609480"

[[constraint]]
  name = "github.com/bgentry/speakeasy"
  revision = "675b82c74c0ed12283ee81ba8a534c8982c07b85"

[[constraint]]
  name = "github.com/blang/semver"
  revision = "4a1e882c79dcf4ec00d2e29fac74b9c8938d5052"

[[constraint]]
  name = "github.com/chzyer/readline"
  revision = "c914be64f07d9998f52bf0d598ec26d457168c0f"

[[constraint]]
  name = "github.com/coreos/etcd"
  revision = "6930e471ed55ef89641a658b9fcb777295d5055b"

[[constraint]]
  name = "github.com/coreos/go-semver"
  version = "v0.2.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "f0777076321ab64f6efc15a82d9d23b98539b943"

[[constraint]]
  name = "github.com/dylanmei/iso8601"
  version = "v0.1.0"

[[constraint]]
  name = "github.com/dylanmei/winrmtest"
  revision = "c2fbb09e6c084fe3ebe95fce0f1cc5297c152026"

[[constraint]]
  name = "github.com/go-ini/ini"
  version = "v1.23.1"

[[constraint]]
  name = "github.com/golang/protobuf"
  revision = "8ee79997227bf9b34611aee7946ae64735e6fd93"

[[constraint]]
  name = "github.com/googleapis/gax-go"
  revision = "da06d194a00e19ce00d9011a13931c3f6f6887c7"

[[constraint]]
  name = "github.com/gophercloud/gophercloud"
  revision = "c5dfe1bc7b150a98b1578bb32f7c138ff9568f1d"

[[constraint]]
  name = "github.com/hashicorp/atlas-go"
  revision = "1792bd8de119ba49b17fd8d3c3c1f488ec613e62"

[[constraint]]
  name = "github.com/hashicorp/consul"
  revision = "610f3c86a089817b5bd5729a3b8c2db33a9ae2b0"

[[constraint]]
  name = "github.com/hashicorp/errwrap"
  revision = "7554cd9344cec97297fa6649b055a8c98c2a1e55"

[[constraint]]
  name = "github.com/hashicorp/go-checkpoint"
  revision = "1545e56e46dec3bba264e41fde2c1e2aa65b5dd4"

[[constraint]]
  name = "github.com/hashicorp/go-cleanhttp"
  revision = "3573b8b52aa7b37b9358d966a898feb387f62437"

[[constraint]]
  name = "github.com/hashicorp/go-getter"
  revision = "a686900cb3753aa644dc4812be91ceaf9fdd3b98"

[[constraint]]
  name = "github.com/hashicorp/go-hclog"
  revision = "b4e5765d1e5f00a0550911084f45f8214b5b83b9"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  revision = "d30f09973e19c1dfcd120b2d9c4f168e68d6b5d5"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a5174f84d7f8ff00fb07ab4ef1f380d32eee0e63"

[[constraint]]
  name = "github.com/hashicorp/go-retryablehttp"
  revision = "6e85be8fee1dcaa02c0eaaac2df5a8fbecf94145"

[[constraint]]
  name = "github.com/hashicorp/go-rootcerts"
  revision = "6bb64b370b90e7ef1fa532be9e591a81c3493e00"

[[constraint]]
  name = "github.com/hashicorp/go-uuid"
  revision = "36289988d83ca270bc07c234c36f364b0dd9c9a7"

[[constraint]]
  name = "github.com/hashicorp/go-version"
  revision = "e96d3840402619007766590ecea8dd7af1292276"

[[constraint]]
  name = "github.com/hashicorp/hcl"
  revision = "a4b07c25de5ff55ad3b8936cea69a79a3d95a855"

[[constraint]]
  name = "github.com/hashicorp/hcl2"
  revision = "44bad6dbf5490f5da17ec991e664df3d017b706f"

[[constraint]]
  name = "github.com/hashicorp/hil"
  revision = "fa9f258a92500514cc8e9c67020487709df92432"

[[constraint]]
  name = "github.com/hashicorp/logutils"
  revision = "0dc08b1671f34c4250ce212759ebd880f743d883"

[[constraint]]
  name = "github.com/hashicorp/serf"
  revision = "e4ec8cc423bbe20d26584b96efbeb9102e16d05f"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "v0.11.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  revision = "9a60bf2a50e4dd1ba4b929a3ccf8072435cbdd0a"

[[constraint]]
  name = "github.com/hashicorp/yamux"
  revision = "d1caa6c97c9fc1cc9e83bbe34d0603f9ff0ce8bd"

[[constraint]]
  name = "github.com/jen20/awspolicyequivalence"
  revision = "3d48364a137a7847c1191b83740052dc7695878e"

[[constraint]]
  name = "github.com/jmespath/go-jmespath"
  revision = "bd40a432e4c76585ef6b72d3fd96fb9b6dc7b68d"

[[constraint]]
  name = "github.com/joyent/triton-go"
  revision = "5a58ad2cdec95cddd1e0a2e56f559341044b04f0"

[[constraint]]
  name = "github.com/kardianos/osext"
  revision = "c2c54e542fb797ad986b31721e1baedf214ca413"

[[constraint]]
  name = "github.com/keybase/go-crypto"
  revision = "93f5b35093ba15e0f86e412cc5c767d5c10c15fd"

[[constraint]]
  name = "github.com/lusis/go-artifactory"
  revision = "7e4ce345df825841661d1b3ffbb1327083d4a22f"

[[constraint]]
  name = "github.com/masterzen/azure-sdk-for-go"
  revision = "ee4f0065d00cd12b542f18f5bc45799e88163b12"

[[constraint]]
  name = "github.com/masterzen/simplexml"
  revision = "4572e39b1ab9fe03ee513ce6fc7e289e98482190"

[[constraint]]
  name = "github.com/masterzen/winrm"
  revision = "a2df6b1315e6fd5885eb15c67ed259e85854125f"

[[constraint]]
  name = "github.com/mattn/go-colorable"
  revision = "9cbef7c35391cca05f15f8181dc0b18bc9736dbb"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  revision = "30a891c33c7cde7b02a981314b4228ec99380cca"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "v1.0.1"

[[constraint]]
  name = "github.com/mitchellh/cli"
  revision = "65fcae5817c8600da98ada9d7edf26dd1a84837b"

[[constraint]]
  name = "github.com/mitchellh/colorstring"
  revision = "8631ce90f28644f54aeedcb3e389a85174e067d1"

[[constraint]]
  name = "github.com/mitchellh/copystructure"
  revision = "5af94aef99f597e6a9e1f6ac6be6ce0f3c96b49d"

[[constraint]]
  name = "github.com/mitchellh/go-homedir"
  revision = "b8bc1bf767474819792c23f32d8286a45736f1c6"

[[constraint]]
  name = "github.com/mitchellh/go-linereader"
  revision = "07bab5fdd9580500aea6ada0e09df4aa28e68abd"

[[constraint]]
  name = "github.com/mitchellh/go-testing-interface"
  revision = "9a441910b16872f7b8283682619b3761a9aa2222"

[[constraint]]
  name = "github.com/mitchellh/go-wordwrap"
  revision = "ad45545899c7b13c020ea92b2072220eefad42b8"

[[constraint]]
  name = "github.com/mitchellh/hashstructure"
  revision = "6b17d669fac5e2f71c16658d781ec3fdd3802b69"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"

[[constraint]]
  name = "github.com/mitchellh/panicwrap"
  revision = "ba9e1a65e0f7975f055d50a2c0201c50d941c24c"

[[constraint]]
  name = "github.com/mitchellh/prefixedio"
  revision = "6e6954073784f7ee67b28f2d22749d6479151ed7"

[[constraint]]
  name = "github.com/mitchellh/reflectwalk"
  revision = "92573fe8d000a145bfebc03a16bc22b34945867f"

[[constraint]]
  name = "github.com/nu7hatch/gouuid"
  revision = "179d4d0c4d8d407a32af483c2354df1d2c91e6c3"

[[constraint]]
  name = "github.com/packer-community/winrmcp"
  revision = "078cc0a785c9da54158c0775f06f505fc1e867f8"

[[constraint]]
  name = "github.com/pkg/errors"
  revision = "c605e284fe17294bda444b34710735b29d1a9d90"

[[constraint]]
  name = "github.com/posener/complete"
  revision = "f4461a52b6329c11190f11fe3384ec8aa964e21c"

[[constraint]]
  name = "github.com/ryanuber/columnize"
  revision = "0fbbb3f0e3fbdc5bae7c6cd5f6c1887ebfb76360"

[[constraint]]
  name = "github.com/satori/go.uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"

[[constraint]]
  name = "github.com/satori/uuid"
  revision = "b061729afc07e77a8aa4fad0a2fd840958f1942a"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-aws"
  revision = "669207b8fee698ccc3fc47a7b99f812078b7ef87"

[[constraint]]
  name = "github.com/terraform-providers/terraform-provider-openstack"
  revision = "4080a521c6ea4872f38bae658ac17b774eefcfe1"

[[constraint]]
  name = "github.com/ugorji/go"
  revision = "84cb69a8af8316eed8cf4a3c9368a56977850062"

[[constraint]]
  name = "github.com/ulikunitz/xz"
  version = "v0.5.4"

[[constraint]]
  name = "github.com/xanzy/ssh-agent"
  revision = "ba9c9e33906f58169366275e3450db66139a31a9"

[[constraint]]
  name = "github.com/xlab/treeprint"
  revision = "1d6e342255576c977e946a2384fc487a22d3fceb"

[[constraint]]
  name = "github.com/zclconf/go-cty"
  revision = "8bf222d6d03b7b336d013978f3acbfd877da428f"

[[constraint]]
  name = "golang.org/x/crypto"
  revision = "453249f01cfeb54c3d549ddb75ff152ca243f9d8"

[[constraint]]
  name = "golang.org/x/net"
  revision = "f2499483f923065a842d38eb4c7f1927e6fc6e6d"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "314dd2c0bf3ebd592ec0d20847d27e79d0dbe8dd"

[[constraint]]
  name = "golang.org/x/sys"
  revision = "0b25a408a50076fbbcae6b7ac0ea5fbb0b085e79"

[[constraint]]
  name = "golang.org/x/text"
  revision = "e56139fd9c5bc7244c76116c68e500765bb6db6b"

[[constraint]]
  name = "google.golang.org/api"
  revision = "7a7376eff6a51c6a053fcf8e9e50bf01a20f2673"

[[constraint]]
  name = "google.golang.org/appengine"
  version = "v1.0.0"

[[constraint]]
  name = "google.golang.org/genproto"
  revision = "f676e0f3ac6395ff1a529ae59a6670878a8371a6"

[[constraint]]
  name = "google.golang.org/grpc"
  revision = "7657092a1303cc5a6fa3fee988d57c665683a4da"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  revision = "cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b"

